In [1]:
import numpy as np 
import pandas as pd

## Loading the Dataset

In [2]:
df_i= pd.read_csv("Combined_i80.csv")
df_us = pd.read_csv("Combined_us101.csv")

In [3]:
df_i

,Vehicle_ID,Frame_ID,Total_Frames,Global_Time,Local_X,Local_Y,Global_X,Global_Y,v_Length,v_Width,v_Class,v_Vel,v_Acc,Lane_ID,Preceding,Following,Space_Headway,Time_Headway,Location,Period
0,1,12,884,1113433136100,16.884,52.747821,6042842.116,2133117.662,14.3,6.4,2,6.947704,2.188888,2,0,0,0.00,0.00,i80,4:00PM - 4:15PM
1,1,13,884,1113433136200,16.938,53.454997,6042842.012,2133118.909,14.3,6.4,2,7.195818,3.152102,2,0,0,0.00,0.00,i80,4:00PM - 4:15PM
2,1,14,884,1113433136300,16.991,54.190893,6042841.908,2133120.155,14.3,6.4,2,7.522104,3.871618,2,0,0,0.00,0.00,i80,4:00PM - 4:15PM
3,1,15,884,1113433136400,17.045,54.961816,6042841.805,2133121.402,14.3,6.4,2,7.896343,4.184370,2,0,0,0.00,0.00,i80,4:00PM - 4:15PM
4,1,16,884,1113433136500,17.098,55.771003,6042841.701,2133122.649,14.3,6.4,2,8.287402,3.906572,2,0,0,0.00,0.00,i80,4:00PM - 4:15PM
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3145720,1757,6959,1386,1113438260800,29.320,654.857278,6042779.679,2133721.623,30.3,8.5,3,0.000000,-0.000091,3,1744,1764,158.90,9999.99,i80,5:15PM - 5:30PM
3145721,1757,6960,1386,1113438260900,29.320,654.857278,6042779.679,2133721.623,30.3,8.5,3,0.000000,0.000089,3,1744,1764,159.68,9999.99,i80,5:15PM - 5:30PM
3145722,1757,6961,1386,1113438261000,29.320,654.857278,6042779.679,2133721.623,30.3,8.5,3,0.000000,-0.000159,3,1744,1764,160.65,9999.99,i80,5:15PM - 5:30PM
3145723,1757,6962,1386,1113438261100,29.320,654.857278,6042779.679,2133721.623,30.3,8.5,3,0.000000,0.000182,3,1744,1764,161.68,9999.99,i80,5:15PM - 5:30PM
3145724,1757,6963,1386,1113438261200,29.320,654.857278,6042779.684,2133721.583,30.3,8.5,3,0.000000,-0.000287,3,1744,1764,162.69,9999.99,i80,5:15PM - 5:30PM

In [4]:
df_i.columns

Index(['Vehicle_ID', 'Frame_ID', 'Total_Frames', 'Global_Time', 'Local_X',
       'Local_Y', 'Global_X', 'Global_Y', 'v_Length', 'v_Width', 'v_Class',
       'v_Vel', 'v_Acc', 'Lane_ID', 'Preceding', 'Following', 'Space_Headway',
       'Time_Headway', 'Location', 'Period'],
      dtype='object')

#### For this project , we are calculating the inter vehicle distance between two cars so , we removed vehicle who changed the lanes

In [5]:
# Only Non-Lane changing will be taken and removing all Lane changing Vehicle 

previous_lane_id = None
filtered_data = []

for index, row in df_i.iterrows():
    current_vehicle_id = row['Vehicle_ID']
    current_lane_id = row['Lane_ID']
    
    if previous_lane_id is None or current_lane_id == previous_lane_id:
        filtered_data.append(row)
    
    previous_lane_id = current_lane_id

df_i = pd.DataFrame(filtered_data)

In [6]:
## Removing the Zero's from preceding, following , space Headway and Time Headway

df_i = df_i[df_i['Preceding'] != 0]
df_i = df_i[df_i['Following'] != 0]
df_i = df_i[df_i['Space_Headway'] != 0]
df_i = df_i[df_i['Time_Headway'] != 0]

In [7]:
# Just checking the Frame ID variable for how many records of cars in single Frame 
df_i[(df_i['Frame_ID'] == 481)]

,Vehicle_ID,Frame_ID,Total_Frames,Global_Time,Local_X,Local_Y,Global_X,Global_Y,v_Length,v_Width,v_Class,v_Vel,v_Acc,Lane_ID,Preceding,Following,Space_Headway,Time_Headway,Location,Period
469,1,481,884,1113433183000,17.280,568.096538,6042778.483,2133634.247,14.3,6.4,2,22.489895,-1.268826,2,3355,11,27.73,1.21,i80,4:00PM - 4:15PM
1027,2,481,415,1113433183000,3.685,268.670050,6042802.101,2133332.687,15.3,6.4,2,27.152063,1.071819,1,44,17,104.83,4.02,i80,4:00PM - 4:15PM
1601,4,481,749,1113433183000,54.410,493.488176,6042824.683,2133563.656,13.4,5.3,2,21.899384,-0.224600,5,21,27,38.90,1.77,i80,4:00PM - 4:15PM
3885,11,481,864,1113433183000,18.218,511.006948,6042786.698,2133575.973,17.3,8.4,2,20.421893,0.544643,2,1,24,58.80,2.88,i80,4:00PM - 4:15PM
4959,13,481,948,1113433183000,42.247,483.720347,6042813.790,2133552.604,14.8,6.4,2,22.093553,0.599321,4,15,66,43.30,2.07,i80,4:00PM - 4:15PM
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1104185,467,481,584,1113436815000,17.139,177.532258,6042826.765,2133242.870,17.8,8.4,2,34.060427,-3.193555,2,456,472,103.96,2.93,i80,5:00PM - 5:15PM
2108043,12,481,1450,1113437613000,41.695,170.313848,6042851.656,2133241.695,13.8,7.3,2,4.216905,-0.000044,4,5,22,36.89,8.74,i80,5:15PM - 5:30PM
2111825,22,481,1528,1113437613000,40.348,135.899688,6042854.767,2133205.817,13.3,6.8,2,4.162023,2.425672,4,12,29,36.01,4.89,i80,5:15PM - 5:30PM
2116939,29,481,1388,1113437613000,39.873,116.875971,6042856.479,2133188.278,15.3,6.9,2,0.000000,0.789570,4,22,37,17.52,9999.99,i80,5:15PM - 5:30PM
2119907,37,481,1430,1113437613000,41.784,88.911015,6042861.766,2133161.206,13.8,7.8,2,0.130876,0.366222,4,29,50,27.57,55.14,i80,5:15PM - 5:30PM

In [8]:
df_i[(df_i['Frame_ID'] == 481) & (df_i['Vehicle_ID']==3355)]

Empty DataFrame
Columns: [Vehicle_ID, Frame_ID, Total_Frames, Global_Time, Local_X, Local_Y, Global_X, Global_Y, v_Length, v_Width, v_Class, v_Vel, v_Acc, Lane_ID, Preceding, Following, Space_Headway, Time_Headway, Location, Period]
Index: []

In [9]:
df_i.to_csv("Transformation_1.csv")