In [1]:
import numpy as np 
import pandas as pd

In [2]:
df_i = pd.read_csv("Transformation_1.csv")

In [4]:
df_i = df_i.drop('Unnamed: 0', axis = 1)
df_i

,Vehicle_ID,Frame_ID,Total_Frames,Global_Time,Local_X,Local_Y,Global_X,Global_Y,v_Length,v_Width,v_Class,v_Vel,v_Acc,Lane_ID,Preceding,Following,Space_Headway,Time_Headway,Location,Period
0,1,481,884,1113433183000,17.280,568.096538,6042778.483,2133634.247,14.3,6.4,2,22.489895,-1.268826,2,3355,11,27.73,1.21,i80,4:00PM - 4:15PM
1,1,482,884,1113433183100,17.286,570.339191,6042778.197,2133636.562,14.3,6.4,2,22.363148,-1.306286,2,3355,11,28.27,1.26,i80,4:00PM - 4:15PM
2,1,483,884,1113433183200,17.291,572.568939,6042777.928,2133638.743,14.3,6.4,2,22.231830,-1.361708,2,3355,11,28.90,1.33,i80,4:00PM - 4:15PM
3,1,484,884,1113433183300,17.297,574.785277,6042777.668,2133640.849,14.3,6.4,2,22.094923,-1.442212,2,3355,11,29.64,1.42,i80,4:00PM - 4:15PM
4,1,485,884,1113433183400,17.301,576.987631,6042777.419,2133642.862,14.3,6.4,2,21.952162,-1.503987,2,3355,11,30.44,1.50,i80,4:00PM - 4:15PM
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2852877,1757,6959,1386,1113438260800,29.320,654.857278,6042779.679,2133721.623,30.3,8.5,3,0.000000,-0.000091,3,1744,1764,158.90,9999.99,i80,5:15PM - 5:30PM
2852878,1757,6960,1386,1113438260900,29.320,654.857278,6042779.679,2133721.623,30.3,8.5,3,0.000000,0.000089,3,1744,1764,159.68,9999.99,i80,5:15PM - 5:30PM
2852879,1757,6961,1386,1113438261000,29.320,654.857278,6042779.679,2133721.623,30.3,8.5,3,0.000000,-0.000159,3,1744,1764,160.65,9999.99,i80,5:15PM - 5:30PM
2852880,1757,6962,1386,1113438261100,29.320,654.857278,6042779.679,2133721.623,30.3,8.5,3,0.000000,0.000182,3,1744,1764,161.68,9999.99,i80,5:15PM - 5:30PM
2852881,1757,6963,1386,1113438261200,29.320,654.857278,6042779.684,2133721.583,30.3,8.5,3,0.000000,-0.000287,3,1744,1764,162.69,9999.99,i80,5:15PM - 5:30PM

In [5]:
# Convert the input variables from feet to meters in df_i DataFrame
df_i['v_Length'] = df_i['v_Length'] * 0.3048
df_i['Space_Headway'] = df_i['Space_Headway'] * 0.3048
df_i['v_Vel'] = df_i['v_Vel'] * 0.3048
df_i['v_Acc'] = df_i['v_Acc'] * 0.3048
df_i['Local_X'] = df_i['Local_X'] * 0.3048
df_i['Local_Y'] = df_i['Local_Y'] * 0.3048

In [7]:
## Merge DataFrame based on Preceding Vehicle ID and Frame ID
df_merged = df_i.merge(df_i, left_on=['Preceding', 'Frame_ID'], right_on=['Vehicle_ID', 'Frame_ID'], suffixes=('', '_preceding'))

In [8]:
df_merged

,Vehicle_ID,Frame_ID,Total_Frames,Global_Time,Local_X,Local_Y,Global_X,Global_Y,v_Length,v_Width,...,v_Class_preceding,v_Vel_preceding,v_Acc_preceding,Lane_ID_preceding,Preceding_preceding,Following_preceding,Space_Headway_preceding,Time_Headway_preceding,Location_preceding,Period_preceding
0,2,372,415,1113433172100,1.737970,29.656915,6042825.039,2133164.183,4.66344,6.4,...,2,1.113693,0.849915,1,3355,2,33.933384,40.93,i80,4:00PM - 4:15PM
1,2,373,415,1113433172200,1.742846,29.798545,6042824.992,2133164.698,4.66344,6.4,...,2,1.199905,0.955930,1,3355,2,34.216848,43.51,i80,4:00PM - 4:15PM
2,2,374,415,1113433172300,1.748028,29.925816,6042824.945,2133165.213,4.66344,6.4,...,2,1.296094,1.058899,1,3355,2,34.497264,48.37,i80,4:00PM - 4:15PM
3,2,375,415,1113433172400,1.753210,30.038956,6042824.898,2133165.728,4.66344,6.4,...,2,1.401743,1.154087,1,3355,2,34.832544,57.43,i80,4:00PM - 4:15PM
4,2,376,415,1113433172500,1.758086,30.139771,6042824.851,2133166.243,4.66344,6.4,...,2,1.515577,1.180521,1,3355,2,35.240976,68.41,i80,4:00PM - 4:15PM
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3193221,1757,6959,1386,1113438260800,8.936736,199.600498,6042779.679,2133721.623,9.23544,8.5,...,2,1.921670,0.278867,3,1735,1757,12.371832,5.69,i80,5:15PM - 5:30PM
3193222,1757,6960,1386,1113438260900,8.936736,199.600498,6042779.679,2133721.623,9.23544,8.5,...,2,1.950145,0.283335,3,1735,1757,12.405360,4.66,i80,5:15PM - 5:30PM
3193223,1757,6961,1386,1113438261000,8.936736,199.600498,6042779.679,2133721.623,9.23544,8.5,...,2,1.979865,0.303436,3,1735,1757,12.380976,4.20,i80,5:15PM - 5:30PM
3193224,1757,6962,1386,1113438261100,8.936736,199.600498,6042779.679,2133721.623,9.23544,8.5,...,2,2.012205,0.335061,3,1735,1757,12.335256,4.04,i80,5:15PM - 5:30PM
3193225,1757,6963,1386,1113438261200,8.936736,199.600498,6042779.684,2133721.583,9.23544,8.5,...,2,2.047770,0.367108,3,1735,1757,12.298680,4.01,i80,5:15PM - 5:30PM

In [9]:
df_merged.to_csv('merged.csv')

In [10]:
df_merged[['Vehicle_ID', 'Preceding']]

         Vehicle_ID  Preceding
0                 2         44
1                 2         44
2                 2         44
3                 2         44
4                 2         44
...             ...        ...
3193221        1757       1744
3193222        1757       1744
3193223        1757       1744
3193224        1757       1744
3193225        1757       1744

[3193226 rows x 2 columns]